# Introduction

In the following analysis, we will talk about how one can create an NLP to detect whether the news is real or fake.
Nowadays, fake news has become a common trend. Even trusted media houses are known to spread fake news and are losing their credibility. So, how can we trust any news to be real or fake?


# Dataset

1. train.csv: A full training dataset with the following attributes:
2. id: unique id for a news article
3. title: the title of a news article
4. author: author of the news article
5. text: the text of the article; could be incomplete
6. label: a label that marks the article as potentially unreliable.
Where 1: unreliable and 0: reliable.

# Contents


1. Introduction
2. Dataset
3. Importing important libraries
4. Reading dataset
5. Data Pre-Processing
6. Building model
7. Spiliting and Training
8. Submission file
9. Conclusion

# Importing important libraries

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# Reading dataset

In [5]:
Train = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSphVXx2nfjFW_vqkgnrAlqfC7rpj-9zUH56SUeW5EGQnQe-B-Y4LJz2UtJKkNRzmgPK694aFSMxFhs/pub?gid=1119098625&single=true&output=csv")


In [6]:
# here we are printing first five lines of our train dataset
Train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

# Data Pre-Processing

In [7]:
# here we are Getting the Independent Features
X=Train.drop('label',axis=1)

In [8]:
# printing head of our independent features
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [9]:
# here we are printing shape of our dataset
Train.shape


(5191, 5)

In [10]:
# here we are checking if there is null value or not
Train.isnull().sum()

id          0
title     147
author    495
text       42
label       0
dtype: int64

In [11]:
# here we are droping NaN values from our dataset
Train=Train.dropna()

In [12]:
# here we are checking again if there is any NaN value or not
Train.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [13]:
Train.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
7   PARIS  —   France chose an idealistic, traditi...      0  
9   A week before Michael T. Flynn resigned as nat...      0  
10  Organizing for Action, the activist group that...      0  
11  The BBC produced spoof on the “Real Housewives...      0

as above we are observing that after removing NaN values index number 6 and number 8 is missing because they are NaN value so they are get removed so for managing index we have to do index reseting

In [14]:
# here we are copying our dataset .
Train=Train.copy()

In [15]:
# here we are reseting our index
Train.reset_index(inplace=True)

In [16]:
# here we are printing our first 10 line of dataset for checking indexing
Train.head(10)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  PARIS  —   France chose an idealistic, traditi...      0  
7  A week before Michael T. Flynn resigned as nat...      0  
8  Organizing for Action, the activist group that...      0  
9  The BBC produced spoof on the “Real Housewives...      0

In [17]:
x=Train['title']
# here we are making independent features
y=Train['label']
y.shape

(4519,)

In [18]:
# here we are importing nltk,stopwords and porterstemmer we are using stemming on the text 
# we have and stopwords will help in removing the stopwords in the text

#re is regular expressions used for identifying only words in the text and ignoring anything else
import nltk
nltk.download('stopwords')
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [19]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(Train)):
    review = re.sub('[^a-zA-Z]', ' ', Train['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus[30]

'russia move ban jehovah wit extremist new york time'

In [21]:
# here we are setting vocabulary size
voc_size=5000

In [22]:
# here we are performing one hot representation
from tensorflow.keras.preprocessing.text import one_hot
one_hot_rep=[one_hot(words,voc_size)for words in corpus] 

In [23]:
# here we are printing length of first line
len(one_hot_rep[0])

10

In [24]:
# here we are printing length of 70 line
len(one_hot_rep[70])

9

In [25]:
# here we are importing library for doind padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# here we are specifying a sentence length so that every sentence in the corpus will be of same length

sentence_length=25

# here we are using padding for creating equal length sentences


embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0 ...  432 2772  183]
 [   0    0    0 ... 1104 4093 4231]
 [   0    0    0 ...   24 4113 2326]
 ...
 [   0    0    0 ... 3152  585 4231]
 [   0    0    0 ... 3472  424 1395]
 [   0    0    0 ... 1178 2479 4231]]


# Building Models

In [26]:
# here we are imporitng important libraries for building model
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
 

In [27]:
#Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sentence_length))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [28]:
z =np.array(embedded_docs)
y =np.array(y)

In [29]:
# here we are printing shape 
z.shape,y.shape

((4519, 25), (4519,))

# Spiliting and Training

In [30]:
# here we are splitting the data for training and testing the model

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(z, y, test_size=0.10, random_state=42)


In [31]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
64/64 [==============================] - 10s 117ms/step - loss: 0.5678 - accuracy: 0.6727 - val_loss: 0.3622 - val_accuracy: 0.8540
Epoch 2/20
64/64 [==============================] - 7s 102ms/step - loss: 0.2349 - accuracy: 0.9142 - val_loss: 0.2282 - val_accuracy: 0.9093
Epoch 3/20
64/64 [==============================] - 7s 109ms/step - loss: 0.1246 - accuracy: 0.9577 - val_loss: 0.2206 - val_accuracy: 0.9071
Epoch 4/20
64/64 [==============================] - 6s 91ms/step - loss: 0.0825 - accuracy: 0.9749 - val_loss: 0.2389 - val_accuracy: 0.9226
Epoch 5/20
64/64 [==============================] - 7s 107ms/step - loss: 0.0576 - accuracy: 0.9845 - val_loss: 0.2635 - val_accuracy: 0.9248
Epoch 6/20
64/64 [==============================] - 6s 92ms/step - loss: 0.0334 - accuracy: 0.9907 - val_loss: 0.3363 - val_accuracy: 0.8982
Epoch 7/20
64/64 [==============================] - 7s 108ms/step - loss: 0.0254 - accuracy: 0.9929 - val_loss: 0.3070 - val_accuracy: 0.9159
Epoch 8

In [34]:
  # here we are loading our test dataset for prediction

Test=pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTTDJSsicLF-aAUAo1Fcjsl26kfPda3FHZMmtila1zNVn7f39vcBv3O5E4AdkShvG73MNvZHM9lKPWv/pub?gid=130825360&single=true&output=csv') 
Test_id=Test["id"]

In [35]:
Test_id

0       20800
1       20801
2       20802
3       20803
4       20804
        ...  
5195    25995
5196    25996
5197    25997
5198    25998
5199    25999
Name: id, Length: 5200, dtype: int64

In [36]:
# here we are printing first 5 line of our dataset
Test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [37]:
# here we are removing these columns as they are not so important
Test=Test.drop(['text','id','author'],axis=1)

In [38]:
# printing first 5 line of our dataset
Test.head()

title
0  Specter of Trump Loosens Tongues, if Not Purse...
1  Russian warships ready to strike terrorists ne...
2  #NoDAPL: Native American Leaders Vow to Stay A...
3  Tim Tebow Will Attempt Another Comeback, This ...
4                    Keiser Report: Meme Wars (E995)

In [39]:
# here we are checking if null values in the test dataset or not

Test.isnull().sum()

title    122
dtype: int64

In [40]:
Test.fillna('fake fake fake',inplace=True)
# here we are filling NaN value with "fake,fake,fake".we cannot drop the NaN value because
# as the solution file that we have to submitted in kaggle expects 
# it to have 5200 rows so we can't drop rows in the test dataset

In [41]:
# here we are printing shape
Test.shape

(5200, 1)

In [42]:
# here we are creating corpus for the test dataset exactly the same as we created for the 
# training dataset
ps = PorterStemmer()
corpus_test = []
for i in range(0, len(Test)):
    review = re.sub('[^a-zA-Z]', ' ',Test['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus_test.append(review)

In [43]:
corpus[30]

'russia move ban jehovah wit extremist new york time'

In [44]:
# here we are creating one hot representation for the test corpus

one_hot_rep_Test=[one_hot(words,voc_size)for words in corpus_test] 

In [45]:
# here we are doing padding for the test dataset
sentence_length=25

embedded_docs_test=pad_sequences(one_hot_rep_Test,padding='pre',maxlen=sentence_length)
print(embedded_docs_test)

[[   0    0    0 ...   21 3239 2071]
 [   0    0    0 ... 2463  485 2007]
 [   0    0    0 ...  131  693 2799]
 ...
 [   0    0    0 ...   21 3239 2071]
 [   0    0    0 ...  907 1737 1671]
 [   0    0    0 ...   21 3239 2071]]


In [46]:
x_test=np.array(embedded_docs_test)

In [51]:
#making predictions for the test dataset

check = model.predict (x_test)


163/163 [==============================] - 3s 19ms/step


In [52]:
check

array([[1.6658818e-12],
       [9.9994475e-01],
       [7.8112382e-05],
       ...,
       [8.0288082e-08],
       [9.7036022e-01],
       [3.7283417e-08]], dtype=float32)

In [53]:
check.shape

(5200, 1)

In [55]:
Test.shape

(5200, 1)

# Submission File

In [56]:
val=[]
for i in check:
    val.append(i[0])

In [57]:
submission = pd.DataFrame({'id':Test_id, 'label':val})
submission.shape

(5200, 2)

In [61]:
submission.head()

id         label
0  20800  1.665882e-12
1  20801  9.999447e-01
2  20802  7.811238e-05
3  20803  3.883467e-10
4  20804  9.655277e-01

In [68]:
#saving the submission file
submit_sample.to_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRIuDM0OI3-7jV5KlmgVfx1LO2B0ILTcqrDoGkAtuSMhHF8ZQgkGsokSIdYpEwyLbsKi4fmp6Jqf6_M/pub?gid=1278328331&single=true&output=csv',index=False)

NameError: ignored

# Conclusion

Thanks for reading. I hope you like my analysis and found it to be helpful. If you have any questions or suggestions, feel free to write them down in the comment section.